base_dev_dir: /share/portal/pd337

hydra:
  run:
    dir: '${base_dev_dir}/xskill/experiment/segment_wise_dist/${now:%Y-%m-%d_%H-%M-%S}'

proto_path: '/share/portal/pd337/xskill/experiment/pretrain/real_easy/ckpt_149/prototype.zarr'

video_path: '/share/portal/pd337/xskill/datasets/portal_kitchen/'
save_path: '/share/portal/pd337/xskill/datasets/portal_kitchen/'


