base_dev_dir: '/share/portal/pd337'

resize_shape: [224,224]
data_path: ${base_dev_dir}/xskill/datasets/portal_table
task_json_path: null
# exp_path: '${base_dev_dir}/xskill/experiment/pretrain/real_pep_tart'
exp_path: /share/portal/pd337/xskill/experiment/pretrain/2024-05-12_23-49-46
human_type: 'pep_tart'
ckpt: 179
device: 'cuda:0'

correct_thresholds: 10
save_clips: True
clip_path: '${exp_path}/gifs'

is_lookup: False
nearest_neighbor_data_dirs: ${exp_path}/${human_type}_l2/ckpt_${ckpt} 
paired_proto_dirs: ${exp_path}/${human_type}_encode_protos/ckpt_${ckpt} 
save_lookups: False


