hydra:
  output_subdir: null
  
base_dev_dir: '/share/portal/sak299'

dataset_dir: '${base_dev_dir}/xskill/datasets/kitchen/small_kitchen_demos_multitask'
start_eps: 600
end_eps: 604
res: 384
embodiment: 'robot'
save_dir: '${base_dev_dir}/xskill/datasets/small_kitchen_dataset/${embodiment}'
