base_dev_dir: '/share/portal/pd337'
base_user_dir: '/share/portal/sak299'

hydra:
  run:
    dir: '/share/portal/sak299/xskill/experiment/label_sim_kitchen/${now:%Y-%m-%d_%H-%M-%S}'

resize_shape: [124,124]
data_path: '${base_dev_dir}/xskill/datasets/kitchen_dataset'
save_data_path: '${base_user_dir}/xskill/datasets/kitchen_dataset'
exp_path: '${base_dev_dir}/xskill/experiment/pretrain/has_79_epochs'
ckpt: 79
device: 'cuda:0'
plot_top_k: null
verbose: True