base_dev_dir: '/home/portal/sak299'

hydra:
  run:
    dir: '${base_dev_dir}/xskill/experiment/label_sim_kitchen/${now:%Y-%m-%d_%H-%M-%S}'

resize_shape: [124,124]
data_path: '${base_dev_dir}/xskill/small_datasets/kitchen_dataset'
exp_path: '${base_dev_dir}/xskill/experiment/pretrain/2024-03-01_15-05-45/'
ckpt: 79
device: 'cuda:0'
plot_top_k: null
verbose: True