hydra:
  output_subdir: null
  
base_dev_dir: '/share/portal/hcn9'

dataset_dir: '${base_dev_dir}/xskill/datasets/kitchen/small_kitchen'
start_eps: 0
end_eps: 4
res: 384
embodiment: 'human'

store_video: True
video_path: '${base_dev_dir}/xskill/datasets/kitchen/${embodiment}'
