base_dev_dir: '/share/portal/pd337'

resize_shape: [124,124]
data_path: ${base_dev_dir}/xskill/datasets/kitchen_dataset
task_json_path: ${data_path}/task_completions.json
exp_path: '${base_dev_dir}/xskill/experiment/pretrain/orig_batch'
human_type: 'human_segments_paired'
ckpt: 79
device: 'cuda:0'

correct_thresholds: 10
save_clips: True
clip_path: '${exp_path}/gifs_segments'

is_lookup: False
nearest_neighbor_data_dirs: ${exp_path}/${human_type}_l2/ckpt_${ckpt} 
paired_proto_dirs: ${exp_path}/${human_type}_encode_protos/ckpt_${ckpt} 
save_lookups: True

ot_lookup: False
tcc_lookup: False


