base_dev_dir: '/share/portal/pd337'

resize_shape: [124,124]
data_path: ${base_dev_dir}/xskill/datasets/kitchen_dataset
# exp_path: '${base_dev_dir}/xskill/experiment/pretrain/ot_pairing_xskill_2024-05-28_11-48-01'
exp_path: '${base_dev_dir}/xskill/experiment/pretrain/orig_batch'

ckpt: 79
human_type: 'human_segments_paired_sample'
device: 'cuda:0'
verbose: True

frame_sampler:
  _target_: xskill.dataset.frame_samplers.UniformDownSampleSampler
  offset: 0
  num_frames: 30
  downsample_ratio: 1

num_chop: 4